### PR TITLE
Comment unsupported code

### PR DESCRIPTION
**Pull request by sangimed**
After the facebook API latest update (2.8 as of 10/05/2016) getUserProfile() is no longer valid.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sangimed Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-facebook&pullRequestId=23)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-accessing-facebook&pullRequestId=23) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sangimed Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-facebook&pullRequestId=23)!

**Comment by dsyer** [comment]
Works for me. What is the purpose of this change?

**Comment by ninadpchaudhari** [comment]
Commenting that part is fine,
but the "hello" view expects a "facebookProfile" attribute.

We should consider https://github.com/spring-guides/gs-accessing-facebook/pull/28 instead.

hello.html => ${facebookProfile.name}

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.

**Pull request closed without merging**
