### PR TITLE
fixed the "deprecated bio" exception due to FB api change. 

### PR DESCRIPTION
**Pull request by creactiviti**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@creactiviti Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-facebook&pullRequestId=28)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-accessing-facebook&pullRequestId=28) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@creactiviti Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-facebook&pullRequestId=28)!

**Comment by ninadpchaudhari** [comment]
Seriously, why hasn't this been merged yet!

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.

**Pull request closed without merging**
